version: "3.8"
services:

  flask:
    build: "flask"
    restart: "always"
    depends_on:
      - memcached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`hostname.example.com`) && PathPrefix(`/py/`)"
      - "traefik.http.routers.flask.entrypoints=web"
    volumes:
      - './.config.yml:/app/.config.yml' 
  
  js:
    build: "js"
    restart: "always"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.js.rule=Host(`hostname.example.com`)"
      - "traefik.http.routers.js.entrypoints=npm"
    volumes:
      - './.config.yml:/tox_app/.config.yml'
  
  memcached:
    image: memcached:1-alpine
    entrypoint:
      - memcached
      - -m 256
    expose:
      - "11211"

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.npm.address=:3001"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

###
# Расскомментировать для поднятия PSQL сервера
# Настройки должны совпадать с теми, что в .config.yml
# Обязательно поставить postgis!
# 
# В качестве db.host в этом случае будет "psql" (имя службы docker-compose)
###
  # psql:
    # image: postgis/postgis:13-master
    # alias: "psql"
    # restart: always
    # ports:
      # - 5432:5432
    # volumes:
    # # место хранения файлов снаружи контейнера
      # - '/srv/psql:/var/lib/postgresql/data/pgdata'
    # environment:
      # POSTGRES_PASSWORD: somePasswordHere
      # POSTGRES_USER: user
      # POSTGRES_DB: db
      # # место хранения файлов внутри контейнера
      # PGDATA: /var/lib/postgresql/data/pgdata
